version: '3.9'

services:
  jenkins:
    image: jenkins_custom
    container_name: jenkins_instance
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    restart: unless-stopped

  nexus3:
    image: sonatype/nexus3
    container_name: nexus3
    ports:
      - "8081:8081" # UI and Artifact API (by jenkins)
    volumes:
      - nexus-data:/nexus-data

  postgresql:
    image: postgres:18-alpine
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - postgresql
    ports:
      - "80:9000" # UI
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgresql:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
    restart: unless-stopped

volumes:
  postgres-data:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:
  nexus-data:
